apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook
spec:
  progressDeadlineSeconds: 9
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook
  template:
    metadata:
      labels:
        app: guestbook
    spec:
      containers:
      - image: ghcr.io/emilyxinyi/guestbook:0.1.15
        name: guestbook
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: guestbook
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: guestbook
