apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: test
  namespace: guestbook
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: guestbook
    sources:
      direct: true
  promotionTemplate:
    spec:
      vars:
      - name: app
        value: guestbook
      - name: imageRepo 
        value: ghcr.io/emilyxinyi/${{ vars.app }}
      steps:
      - task: 
          name: standard-process
      - uses: http
        as: cat-facts
        config:
          method: GET
          url: https://www.catfacts.net/api/
          outputs:
          - name: status
            fromExpression: response.status
          - name: fact1
            fromExpression: response.body.facts[0]
          - name: fact2
            fromExpression: response.body.facts[1]
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: uat
  namespace: guestbook
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: guestbook
    sources:
      stages:
      - test
      # requiredSoakTime: 2m0s
  promotionTemplate:
    spec:
      vars:
      - name: gitRepo
        value: https://github.com/fuskovic/kargo
        name: imageRepo
        value: ghcr.io/emilyxinyi/guestbook
      steps:
      - uses: git-clone
        config:
          repoURL: https://github.com/fuskovic/kargo.git
          checkout:
          - branch: main
            path: ./src
          - branch: stage/uat
            create: true
            path: ./out
      - uses: git-clear
        config:
          path: ./out
      - uses: kustomize-set-image
        as: update-image
        config:
          path: ./src/guestbook/stages/uat
          images:
          - image: ghcr.io/emilyxinyi/guestbook
            tag: ${{ imageFrom(vars.imageRepo).Tag }}
      - uses: kustomize-build
        config:
          path: ./src/guestbook/stages/uat
          outPath: ./out/manifests.yaml
      - uses: git-commit
        as: commit
        config:
          path: ./out
          message: | 
            ${{ ctx.stage }}: ${{ outputs['update-image'].commitMessage}}
      - uses: git-push
        as: push
        config:
          path: ./out
          targetBranch: stage/uat
          # generateTargetBranch: true
      - uses: argocd-update
        config:
          apps:
          - name: guestbook-uat
            sources:
            - repoURL: https://github.com/fuskovic/kargo.git
      # - uses: http
      #   as: snow
      #   config:
      #     method: POST
      #     url: https://dev299333.service-now.com/api/now/table/change_request
      #     headers: 
      #     - name: Authorization
      #       value: Basic ${{ toBase64( secrets.snow.username + ":" + secrets.snow.password ) }}
      #       # value: Basic ${{ secrets.snow.hashed }}
      #     - name: Content-Type
      #       value: application/json
      #     - name: Accept
      #       value: application/json
      #     body: |
      #       {
      #         "short_description": "This is a test",
      #         "start_date": "2024-03-01 00:00:00",
      #         "end_date": "2024-03-02 00:00:00"
      #       }
      #     outputs:
      #     - name: status
      #       fromExpression: response.status
          # - name: number
          #   fromExpression: response.body.results.number
          # - name: fact1
          #   fromExpression: response.body.facts[0]
          # - name: fact2
          #   fromExpression: response.body.facts[1]
  verification:
    analysisTemplates:
    - name: guestbook-verification-3
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-useast
  namespace: guestbook
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: guestbook
    sources:
      stages:
      - uat
  promotionTemplate:
    spec:
      vars:
      - name: gitRepo
        value: https://github.com/fuskovic/kargo
        name: imageRepo
        value: ghcr.io/emilyxinyi/guestbook
      steps:
      - uses: git-clone
        config:
          repoURL: https://github.com/fuskovic/kargo.git
          checkout:
          - branch: main
            path: ./src
          # - commit: ${{ commitFrom(vars.gitRepo) }}
          #   path: ./src
          - branch: stage/prod-useast
            create: true
            path: ./out
      - uses: git-clear
        config:
          path: ./out
      - uses: kustomize-set-image
        as: update-image
        config:
          path: ./src/guestbook/base
          images:
          - image: ghcr.io/emilyxinyi/guestbook
            # tag: ${{ imageFrom(ghcr.io/emilyxinyi/guestbook).Tag }}
            tag: ${{ imageFrom(vars.imageRepo).Tag }}
      - uses: kustomize-build
        config:
          path: ./src/guestbook/stages/prod-useast
          outPath: ./out/manifests.yaml
      - uses: git-commit
        as: commit
        config:
          path: ./out
          message: | 
            ${{ ctx.stage }}: ${{ outputs['update-image'].commitMessage}}
      - uses: git-push
        as: push
        config:
          path: ./out
          generateTargetBranch: true
          # targetBranch: stage/prod-useast
      - uses: git-open-pr
        as: open-pr
        config:
          repoURL: https://github.com/fuskovic/kargo.git
          createTargetBranch: true
          sourceBranch: ${{ outputs.push.branch }}
          # targetBranch: stage/${{ ctx.stage }}
          targetBranch: stage/prod-useast
      - uses: git-wait-for-pr
        as: wait-for-pr
        config:
          repoURL: https://github.com/fuskovic/kargo.git
          prNumber: ${{ outputs['open-pr'].pr.id }}
        # spec: 
        #   interval: "5m0s"
      # - uses: compose-output
      #   as: commitNumber
      #   config:
      #     commitNumber: ${{ outputs['wait-for-pr'].commit }}
      - uses: argocd-update
        config:
          apps:
          - name: guestbook-prod-useast
            sources:
            - repoURL: https://github.com/fuskovic/kargo.git
              desiredRevision: ${{ outputs['wait-for-pr'].commit }}
      - uses: compose-output
        as: commit-link
        config:
          url: https://github.com/fuskovic/kargo/commit/${{ outputs['wait-for-pr'].commit }}
      - uses: http
        as: slack-message
        config:
          method: POST
          url: https://slack.com/api/chat.postMessage
          headers:
          - name: Authorization
            value: Bearer ${{ secret('slack').token }}
          - name: Content-Type
            value: application/json
          body: |
            ${{ quote({
              "channel": "C08CPA2KB9A",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "PR merged: " + outputs['commit-link'].url
                  }
                }
              ]
            }) }}
          outputs:
          - name: status
            fromExpression: response.status
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-uswest
  namespace: guestbook
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: guestbook
    sources:
      stages:
      - uat
  promotionTemplate:
    spec:
      vars:
      - name: app
        value: guestbook
      - name: imageRepo 
        value: ghcr.io/emilyxinyi/${{ vars.app }}
      steps:
      - task: 
          name: standard-process
