apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: guestbook
  namespace: guestbook
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  subscriptions:
  - git:
      repoURL: https://github.com/fuskovic/kargo.git
      branch: main
  - image:
      repoURL: ghcr.io/emilyxinyi/guestbook