apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - stage: test
      - stage: uat
      - stage: prod-useast
      - stage: prod-uswest
  template:
    metadata:
      name: guestbook-{{stage}}
      annotations:
        kargo.akuity.io/authorized-stage: guestbook:{{stage}}
    spec:
      project: guestbook
      source:
        repoURL: https://github.com/fuskovic/kargo-testing.git
        targetRevision: stage/{{stage}}
        path: ./
      destination:
        name: in-cluster
        namespace: guestbook-{{stage}}
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
